networks:
  loki:
  traefik-proxy:
    external: true

services:
  loki:
    image: grafana/loki:2.9.17
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - ./loki-data:/var/loki
    command: -config.file=/etc/loki/loki-config.yaml
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - loki

  # prometheus:
  #   image: prom/prometheus:${PROMETHEUS_VERSION:-v3.5.0}
  #   command:
  #     - --web.enable-remote-write-receiver
  #     - --config.file=/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"

  grafana:
    image: grafana/grafana:12.3.1
    environment:
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      # GF_AUTH_ANONYMOUS_ENABLED: "true"
      # GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    ports:
      - "4871:3000"
    depends_on:
      loki:
        condition: service_healthy
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      # - ./.data/grafana:/var/lib/grafana
    networks:
      - loki
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik-proxy"

  alloy:
    image: grafana/alloy:v1.12.1
    command: >
      run
      --server.http.listen-addr=0.0.0.0:12345
      --storage.path=/var/lib/alloy/data
      /etc/alloy/config.alloy
    volumes:
       - ./config.alloy:/etc/alloy/config.alloy
       - /var/run/docker.sock:/var/run/docker.sock
      # - ./.data/alloy:/var/lib/alloy/data
    depends_on:
      loki:
        condition: service_healthy
    ports:
      - "12345:12345"
    networks:
      - loki

